export const CREATE_AD_FAIL = 'CREATE_AD_FAIL';
export const CREATE_AD_SUCCESS = 'CREATE_AD_SUCCESS';
export const CREATE_AD_REQUEST = 'CREATE_AD_REQUEST';


export const ADS_LIST_REQUEST = 'ADS_LIST_REQUEST';
export const ADS_LIST_SUCCESS = 'ADS_LIST_SUCCESS';
export const ADS_LIST_FAIL = 'ADS_LIST_FAIL';

export const AD_DETAILS_REQUEST = 'ADS_DETAILS_REQUEST';
export const AD_DETAILS_SUCCESS = 'ADS_DETAILS_SUCCESS';
export const AD_DETAILS_FAIL = 'ADS_DETAILS_FAIL';


export const VIEW_CONTACT_REQUEST = 'VIEW_CONTACT_REQUEST';
export const VIEW_CONTACT_SUCCESS = 'VIEW_CONTACT_SUCCESS';
export const VIEW_CONTACT_FAIL = 'VIEW_CONTACT_FAIL';


export const VIEW_WHATSAPP_REQUEST = 'VIEW_WHATSAPP_REQUEST';
export const VIEW_WHATSAPP_SUCCESS = 'VIEW_WHATSAPP_SUCCESS';
export const VIEW_WHATSAPP_FAIL = 'VIEW_WHATSAPP_FAIL';

export const AD_DELETE_REQUEST = 'AD_DELETE_REQUEST';
export const AD_DELETE_SUCCESS = 'AD_DELETE_SUCCESS';
export const AD_DELETE_FAIL = 'AD_DELETE_FAIL';
